2021-04-20 11:55:27.0838 TAS.Services.Entities.Management.ClaimEntityManager SubmitOtherTireClaim: exception: A recognition error occurred. [.FirstOrDefault[TAS.Services.Entities.AvailableTireSizesPattern](.Select[<>f__AnonymousType131`2[[<>f__AnonymousType130`2[[TAS.Services.Entities.ArticleMapping, TAS.Services, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[TAS.Services.Entities.AvailableTireSizes, TAS.Services, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], TAS.Services, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[TAS.Services.Entities.AvailableTireSizesPattern, TAS.Services, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]],TAS.Services.Entities.AvailableTireSizesPattern](.Where[<>f__AnonymousType131`2[[<>f__AnonymousType130`2[[TAS.Services.Entities.ArticleMapping, TAS.Services, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[TAS.Services.Entities.AvailableTireSizes, TAS.Services, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], TAS.Services, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[TAS.Services.Entities.AvailableTireSizesPattern, TAS.Services, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]](.Join[<>f__AnonymousType130`2[[TAS.Services.Entities.ArticleMapping, TAS.Services, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[TAS.Services.Entities.AvailableTireSizes, TAS.Services, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]],TAS.Services.Entities.AvailableTireSizesPattern,System.Guid,<>f__AnonymousType131`2[[<>f__AnonymousType130`2[[TAS.Services.Entities.ArticleMapping, TAS.Services, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[TAS.Services.Entities.AvailableTireSizes, TAS.Services, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], TAS.Services, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[TAS.Services.Entities.AvailableTireSizesPattern, TAS.Services, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]](.Join[TAS.Services.Entities.ArticleMapping,TAS.Services.Entities.AvailableTireSizes,System.Guid,<>f__AnonymousType130`2[[TAS.Services.Entities.ArticleMapping, TAS.Services, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[TAS.Services.Entities.AvailableTireSizes, TAS.Services, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]](NHibernate.Linq.NhQueryable`1[TAS.Services.Entities.ArticleMapping], NHibernate.Linq.NhQueryable`1[TAS.Services.Entities.AvailableTireSizes], Quote((am, ) => (am.AvailableTireSizeId)), Quote((ats, ) => (ats.Id)), Quote((am, ats, ) => (new <>f__AnonymousType130`2(am, ats, ))), ), NHibernate.Linq.NhQueryable`1[TAS.Services.Entities.AvailableTireSizesPattern], Quote((<>h__TransparentIdentifier0, ) => (<>h__TransparentIdentifier0.ats.Id)), Quote((atsp, ) => (atsp.AvailableTireSizesId)), Quote((<>h__TransparentIdentifier0, atsp, ) => (new <>f__AnonymousType131`2(<>h__TransparentIdentifier0, atsp, ))), ), Quote((<>h__TransparentIdentifier1, ) => (String.op_Equality(<>h__TransparentIdentifier1.<>h__TransparentIdentifier0.am.ArticleNo, p1))), ), Quote((<>h__TransparentIdentifier1, ) => (TAS.Services.Entities.AvailableTireSizesPattern)), ), )], 
2021-04-20 12:18:16.1167 TAS.Services.Entities.Management.ClaimEntityManager GetPolicyDetailsForView: exception: Object reference not set to an instance of an object., 
2021-04-20 12:18:36.6161 TAS.Services.Entities.Management.ClaimEntityManager GetPolicyDetailsForView: exception: Object reference not set to an instance of an object., 
2021-04-20 12:20:00.4782 TAS.Services.Entities.Management.NotificationEntityManager MoveNext: exception: An error occurred while sending the request., System.Net.WebException: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel. ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
2021-04-20 12:20:02.2166 TAS.Services.Entities.Management.UserEntityManager GetUserById: exception: a different object with the same identifier value was already associated with the session: 97e735f7-8b14-4608-bc8a-97c6e16e6926, of entity: TAS.Services.Entities.UserType, 
2021-04-20 13:13:42.6232 TAS.Web.Controllers.UserController LoginAuth: exception: Value cannot be null.
Parameter name: input, 
2021-04-20 13:13:47.4865 TAS.Web.Controllers.UserController LoginAuth: exception: Value cannot be null.
Parameter name: input, 
2021-04-20 13:13:48.4611 TAS.Web.Controllers.UserController LoginAuth: exception: Value cannot be null.
Parameter name: input, 
2021-04-20 13:13:48.9416 TAS.Web.Controllers.UserController LoginAuth: exception: Value cannot be null.
Parameter name: input, 
2021-04-20 13:13:49.1176 TAS.Web.Controllers.UserController LoginAuth: exception: Value cannot be null.
Parameter name: input, 
